SELECT BOOKNAME, PRICE FROM BOOK;

SELECT PRICE, BOOKNAME FROM BOOK;

SELECT BOOKID, BOOKNAME, PUBLISHER, PRICE FROM BOOK;

SELECT * FROM BOOK;

SELECT PUBLISHER FROM BOOK;

SELECT distinct PUBLISHER FROM BOOK;

SELECT * FROM BOOK WHERE PRICE < 20000;

SELECT * FROM BOOK WHERE PRICE Between 10000 and 20000;

SELECT * FROM BOOK WHERE PRICE >= 10000 and PRICE <= 20000;

SELECT * FROM BOOK WHERE PUBLISHER NOT IN('굿스포츠', '대한미디어');

SELECT BOOKNAME, PUBLISHER FROM BOOK WHERE BOOKNAME LIKE '축구의 역사';

SELECT BOOKNAME, PUBLISHER FROM BOOK WHERE BOOKNAME LIKE '%축구%';

SELECT * FROM BOOK WHERE BOOKNAME LIKE '_구%';

SELECT * FROM BOOK WHERE BOOKNAME LIKE '%축구%' AND PRICE >= 20000;

SELECT * FROM BOOK WHERE PUBLISHER='굿스포츠' OR PUBLISHER='대한미디어';

SELECT * FROM BOOK order by BOOKNAME;

SELECT * FROM BOOK order by PRICE, BOOKNAME;

SELECT * FROM BOOK order by PRICE DESC, PUBLISHER ASC;

SELECT SUM(SALEPRICE) FROM ORDERS;

SELECT SUM(SALEPRICE) AS 총매출 FROM ORDERS;

SELECT SUM(SALEPRICE) AS 총매출 FROM ORDERS WHERE custid=2;

SELECT 
       SUM(SALEPRICE) AS TOTAL, 
       AVG(SALEPRICE) AS AVERAGE, 
       MIN(SALEPRICE) AS MINIMUM, 
       MAX(SALEPRICE) AS MAXIMUM
FROM ORDERS;

SELECT COUNT(*) from ORDERS;

SELECT 
     CUSTID,
     COUNT(*) AS 도서수량, 
     SUM(SALEPRICE) AS 총액 
FROM ORDERS 
GROUP BY CUSTID;

SELECT 
     CUSTID,
     COUNT(*) AS 도서수량 
FROM ORDERS 
WHERE SALEPRICE >= 8000 
GROUP BY CUSTID HAVING COUNT(*) >= 2;

/*1-(1)*/
SELECT BOOKNAME FROM BOOK WHERE BOOKID=1;

/*1-(2)*/
SELECT BOOKNAME FROM BOOK WHERE PRICE >= 20000;
/*1-(3)*/
SELECT SUM(SALEPRICE) AS TOTAL FROM ORDERS
WHERE
     CUSTID = (SELECT CUSTID 
               FROM CUSTOMER 
               WHERE NAME LIKE '박지성');  
               
SELECT SUM(ORDERS.SALEPRICE) AS TOTAL 
FROM ORDERS 
INNER JOIN CUSTOMER 
ON ORDERS.CUSTID = CUSTOMER.CUSTID
WHERE CUSTOMER.NAME LIKE '박지성';

/*1-(4)*/
SELECT COUNT(*) AS TOTAL FROM ORDERS
WHERE
     CUSTID = (SELECT CUSTID 
               FROM CUSTOMER 
               WHERE NAME LIKE '박지성');
/*2-(1)*/
SELECT COUNT(BOOKNAME) FROM BOOK;
/*2-(2)*/
SELECT COUNT(DISTINCT PUBLISHER) AS 출판사총개수 FROM BOOK;
/*2-(3)*/
SELECT NAME,ADDRESS FROM CUSTOMER;
/*2-(4)*/
SELECT ORDERID 
FROM ORDERS 
WHERE ORDERDATE 
BETWEEN '14/7/4' AND '14/7/7';
/*2-(5)*/
SELECT ORDERID 
FROM ORDERS 
WHERE ORDERDATE 
NOT BETWEEN '14/7/4' AND '14/7/7';
/*2-(6)*/
SELECT NAME,ADDRESS FROM CUSTOMER WHERE NAME LIKE '김%';
/*2-(7)*/
SELECT NAME,ADDRESS FROM CUSTOMER WHERE NAME LIKE '김%아' ;

/*3-21,22*/
SELECT *
FROM CUSTOMER,ORDERS
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
ORDER BY CUSTOMER.CUSTID;

/*3-23*/
SELECT CUSTOMER.NAME, SUM(ORDERS.SALEPRICE)
FROM CUSTOMER,ORDERS
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
GROUP BY CUSTOMER.NAME
ORDER BY CUSTOMER.NAME;
